[package]
name = "zorder"
version = "0.1.0"
edition = "2021"
authors = ["Elias Kauppi <elkku.kauppi@gmail.com>"]
description = "Fast Z-order curve conversions"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
